# Generated by Django 2.1 on 2019-06-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='content',
            field=models.CharField(default='nothing here', max_length=300),
        ),
    ]
