# Generated by Django 2.1 on 2019-06-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_auto_20190628_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='content',
            field=models.CharField(default='nothing here', max_length=1000),
        ),
    ]
